"""Export the API contract, or verify the committed copy is current.

    python scripts/export_contract.py           regenerate
    python scripts/export_contract.py --check   fail if out of date

Writes two files:

    openapi.json         REST surface, generated by FastAPI
    events.schema.json   WebSocket surface, generated from the event registry

FastAPI only exports schemas reachable from an HTTP route, so the WebSocket
payloads would otherwise exist only in Python source and the frontend would have
nothing to generate types from. Both files are committed, and CI runs --check so
a contract change without a regeneration fails the build.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic import BaseModel

from app.main import create_app
from app.schemas.events import (
    CLIENT_PAYLOADS,
    SERVER_PAYLOADS,
    ClientEvent,
    ServerEvent,
)

BACKEND = Path(__file__).resolve().parent.parent
OPENAPI = BACKEND / "openapi.json"
EVENTS = BACKEND / "events.schema.json"


def _schema(model: type[BaseModel] | None) -> dict | None:
    return model.model_json_schema() if model else None


def build_events() -> dict:
    return {
        "version": "1.0",
        "description": (
            "C.L.I.P WebSocket contract. Every message is {type, data}; server "
            "messages also carry seq and ts. seq increases monotonically per "
            "session so clients can detect gaps and request replay."
        ),
        "envelopes": {
            "client": ClientEvent.model_json_schema(),
            "server": ServerEvent.model_json_schema(),
        },
        "client_events": {event.value: _schema(model) for event, model in CLIENT_PAYLOADS.items()},
        "server_events": {event.value: _schema(model) for event, model in SERVER_PAYLOADS.items()},
    }


def render_openapi() -> str:
    return json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n"


def render_events() -> str:
    return json.dumps(build_events(), indent=2, sort_keys=True) + "\n"


def _read(path: Path) -> str:
    # newline="" disables translation so a Windows checkout and a Linux CI run
    # compare the same bytes.
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


def _write(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


TARGETS = ((OPENAPI, render_openapi), (EVENTS, render_events))


def check() -> int:
    stale = []
    for path, render in TARGETS:
        if not path.exists() or _read(path) != render():
            stale.append(path.name)

    if stale:
        print(
            f"Out of date: {', '.join(stale)}\n"
            f"The contract changed but the committed copy was not regenerated.\n"
            f"Run: python scripts/export_contract.py"
        )
        return 1

    print(f"{OPENAPI.name} and {EVENTS.name} are up to date")
    return 0


def write() -> int:
    for path, render in TARGETS:
        _write(path, render())

    spec = create_app().openapi()
    print(
        f"{len(spec['paths'])} REST paths, "
        f"{len(spec.get('components', {}).get('schemas', {}))} schemas -> {OPENAPI.name}"
    )
    print(
        f"{len(CLIENT_PAYLOADS)} client events, "
        f"{len(SERVER_PAYLOADS)} server events -> {EVENTS.name}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else write())
