"""add Teams roster persistence

Revision ID: 3cc5df760772
Revises: 9a52bced38c2
Create Date: 2026-09-27 23:09:23.709349

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cc5df760772"
down_revision: str | Sequence[str] | None = "9a52bced38c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams_roster_sync",
        sa.Column("sync_id", sa.UUID(), nullable=False),
        sa.Column("meeting_id", sa.String(length=256), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("source_event_id", sa.String(length=256), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="received", nullable=False),
        sa.Column("participant_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("matched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unmatched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('snapshot', 'participant_joined', 'participant_left')",
            name="ck_teams_roster_sync_event_type",
        ),
        sa.CheckConstraint(
            "status IN ('received', 'processed', 'failed')", name="ck_teams_roster_sync_status"
        ),
        sa.CheckConstraint(
            "duplicate_count >= 0", name="ck_teams_roster_sync_duplicate_count_nonnegative"
        ),
        sa.CheckConstraint(
            "matched_count >= 0", name="ck_teams_roster_sync_matched_count_nonnegative"
        ),
        sa.CheckConstraint(
            "missing_count >= 0", name="ck_teams_roster_sync_missing_count_nonnegative"
        ),
        sa.CheckConstraint(
            "participant_count >= 0", name="ck_teams_roster_sync_participant_count_nonnegative"
        ),
        sa.CheckConstraint(
            "unmatched_count >= 0", name="ck_teams_roster_sync_unmatched_count_nonnegative"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.session_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("sync_id"),
        sa.UniqueConstraint(
            "meeting_id", "source_event_id", name="uq_teams_roster_sync_meeting_source_event"
        ),
    )
    op.create_index(
        op.f("ix_teams_roster_sync_meeting_id"), "teams_roster_sync", ["meeting_id"], unique=False
    )
    op.create_index(
        op.f("ix_teams_roster_sync_session_id"), "teams_roster_sync", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_teams_roster_sync_status"), "teams_roster_sync", ["status"], unique=False
    )
    op.create_table(
        "teams_participant_mapping",
        sa.Column("participant_mapping_id", sa.UUID(), nullable=False),
        sa.Column("sync_id", sa.UUID(), nullable=False),
        sa.Column("record_index", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=256), nullable=True),
        sa.Column("teams_user_id", sa.String(length=256), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("match_status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_status IN ('matched', 'unmatched', 'missing', 'duplicate')",
            name="ck_teams_participant_mapping_match_status",
        ),
        sa.CheckConstraint(
            "record_index >= 0", name="ck_teams_participant_mapping_record_index_nonnegative"
        ),
        sa.ForeignKeyConstraint(["sync_id"], ["teams_roster_sync.sync_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("participant_mapping_id"),
        sa.UniqueConstraint(
            "sync_id", "record_index", name="uq_teams_participant_mapping_sync_record"
        ),
    )
    op.create_index(
        op.f("ix_teams_participant_mapping_match_status"),
        "teams_participant_mapping",
        ["match_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_participant_mapping_sync_id"),
        "teams_participant_mapping",
        ["sync_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_participant_mapping_teams_user_id"),
        "teams_participant_mapping",
        ["teams_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_participant_mapping_tenant_id"),
        "teams_participant_mapping",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_participant_mapping_user_id"),
        "teams_participant_mapping",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_teams_participant_mapping_user_id"), table_name="teams_participant_mapping"
    )
    op.drop_index(
        op.f("ix_teams_participant_mapping_tenant_id"), table_name="teams_participant_mapping"
    )
    op.drop_index(
        op.f("ix_teams_participant_mapping_teams_user_id"), table_name="teams_participant_mapping"
    )
    op.drop_index(
        op.f("ix_teams_participant_mapping_sync_id"), table_name="teams_participant_mapping"
    )
    op.drop_index(
        op.f("ix_teams_participant_mapping_match_status"), table_name="teams_participant_mapping"
    )
    op.drop_table("teams_participant_mapping")
    op.drop_index(op.f("ix_teams_roster_sync_status"), table_name="teams_roster_sync")
    op.drop_index(op.f("ix_teams_roster_sync_session_id"), table_name="teams_roster_sync")
    op.drop_index(op.f("ix_teams_roster_sync_meeting_id"), table_name="teams_roster_sync")
    op.drop_table("teams_roster_sync")
    # ### end Alembic commands ###
