"""create question table

Revision ID: 70bf1eade701
Revises: 89980d5732da
Create Date: 2026-08-06 20:14:31.515061

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70bf1eade701"
down_revision: str | Sequence[str] | None = "89980d5732da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("source_material_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["source_material.id"],
        ),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(op.f("ix_question_session_id"), "question", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_question_source_material_id"), "question", ["source_material_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_source_material_id"), table_name="question")
    op.drop_index(op.f("ix_question_session_id"), table_name="question")
    op.drop_table("question")
    # ### end Alembic commands ###
