"""add live session persistence

Revision ID: 7fb1c9da741b
Revises: 9b1d3f5a7c20
Create Date: 2026-09-20 23:03:58.860765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fb1c9da741b"
down_revision: str | Sequence[str] | None = "9b1d3f5a7c20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_activity",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["user.user_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["session.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_index(
        op.f("ix_session_activity_actor_user_id"),
        "session_activity",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_activity_event_type"), "session_activity", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_session_activity_occurred_at"), "session_activity", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_session_activity_session_id"), "session_activity", ["session_id"], unique=False
    )
    op.create_table(
        "session_participant",
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connection_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "connection_count >= 1", name="ck_session_participant_connection_count_positive"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.session_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["student.student_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("participant_id"),
        sa.UniqueConstraint(
            "session_id", "student_id", name="uq_session_participant_session_student"
        ),
    )
    op.create_index(
        op.f("ix_session_participant_session_id"),
        "session_participant",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_participant_student_id"),
        "session_participant",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "delivered_question",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=30), nullable=True),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("eligible_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("respondent_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "eligible_count >= 0", name="ck_delivered_question_eligible_count_nonnegative"
        ),
        sa.CheckConstraint(
            "respondent_count <= eligible_count",
            name="ck_delivered_question_respondents_within_eligible",
        ),
        sa.CheckConstraint(
            "respondent_count >= 0", name="ck_delivered_question_respondent_count_nonnegative"
        ),
        sa.CheckConstraint(
            "window_seconds >= 0", name="ck_delivered_question_window_seconds_nonnegative"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["question.question_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["session.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("delivery_id"),
        sa.UniqueConstraint(
            "session_id", "question_id", name="uq_delivered_question_session_question"
        ),
    )
    op.create_index(
        op.f("ix_delivered_question_question_id"),
        "delivered_question",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivered_question_session_id"), "delivered_question", ["session_id"], unique=False
    )
    op.create_table(
        "missed_response",
        sa.Column("missed_response_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=30), server_default="window_elapsed", nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"], ["delivered_question.delivery_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["student.student_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("missed_response_id"),
        sa.UniqueConstraint(
            "delivery_id", "student_id", name="uq_missed_response_delivery_student"
        ),
    )
    op.create_index(
        op.f("ix_missed_response_delivery_id"), "missed_response", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_missed_response_student_id"), "missed_response", ["student_id"], unique=False
    )
    op.add_column(
        "dynamic_prompt", sa.Column("escalation", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "dynamic_prompt",
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "dynamic_prompt", sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("dynamic_prompt", "prompt_text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "dynamic_prompt", "trigger_reason", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.execute(
        """
        UPDATE dynamic_prompt
        SET response_status = 'expired'
        WHERE response_status NOT IN ('acknowledged', 'dismissed', 'expired')
        """
    )
    op.execute(
        """
        UPDATE dynamic_prompt
        SET responded_at = timestamp
        WHERE response_status IN ('acknowledged', 'dismissed')
        """
    )
    op.create_check_constraint(
        "ck_dynamic_prompt_escalation_positive", "dynamic_prompt", "escalation >= 1"
    )
    op.create_check_constraint(
        "ck_dynamic_prompt_response_status",
        "dynamic_prompt",
        "response_status IN ('acknowledged', 'dismissed', 'expired')",
    )
    op.drop_column("dynamic_prompt", "timestamp")
    op.add_column("student_response", sa.Column("selected_option", sa.Integer(), nullable=True))
    op.add_column("student_response", sa.Column("free_text", sa.Text(), nullable=True))
    op.add_column("student_response", sa.Column("elapsed_ms", sa.Integer(), nullable=True))
    op.add_column(
        "student_response",
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.execute(
        """
        UPDATE student_response
        SET free_text = answer,
            submitted_at = timestamp
        """
    )
    op.alter_column("student_response", "is_correct", existing_type=sa.BOOLEAN(), nullable=True)
    # Retain the newest answer if a pre-migration database contains multiple
    # responses from one student for the same question.
    op.execute(
        """
        DELETE FROM student_response
        WHERE response_id IN (
            SELECT response_id
            FROM (
                SELECT
                    response_id,
                    row_number() OVER (
                        PARTITION BY session_id, student_id, question_id
                        ORDER BY submitted_at DESC, response_id DESC
                    ) AS duplicate_number
                FROM student_response
            ) AS duplicate_responses
            WHERE duplicate_number > 1
        )
        """
    )
    op.create_unique_constraint(
        "uq_student_response_session_student_question",
        "student_response",
        ["session_id", "student_id", "question_id"],
    )
    op.create_check_constraint(
        "ck_student_response_elapsed_ms_nonnegative",
        "student_response",
        "elapsed_ms IS NULL OR elapsed_ms >= 0",
    )
    op.create_check_constraint(
        "ck_student_response_exactly_one_answer",
        "student_response",
        "(selected_option IS NOT NULL AND free_text IS NULL) OR "
        "(selected_option IS NULL AND free_text IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_student_response_selected_option_nonnegative",
        "student_response",
        "selected_option IS NULL OR selected_option >= 0",
    )
    op.drop_column("student_response", "answer")
    op.drop_column("student_response", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_response",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "student_response",
        sa.Column(
            "answer",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE student_response
        SET answer = COALESCE(free_text, selected_option::text),
            timestamp = submitted_at
        """
    )
    op.alter_column(
        "student_response",
        "answer",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.execute(
        """
        UPDATE student_response
        SET is_correct = false
        WHERE is_correct IS NULL
        """
    )
    op.drop_constraint(
        "ck_student_response_selected_option_nonnegative", "student_response", type_="check"
    )
    op.drop_constraint("ck_student_response_exactly_one_answer", "student_response", type_="check")
    op.drop_constraint(
        "ck_student_response_elapsed_ms_nonnegative", "student_response", type_="check"
    )
    op.drop_constraint(
        "uq_student_response_session_student_question", "student_response", type_="unique"
    )
    op.alter_column("student_response", "is_correct", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("student_response", "submitted_at")
    op.drop_column("student_response", "elapsed_ms")
    op.drop_column("student_response", "free_text")
    op.drop_column("student_response", "selected_option")
    op.add_column(
        "dynamic_prompt",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.execute(
        """
        UPDATE dynamic_prompt
        SET timestamp = COALESCE(responded_at, sent_at),
            prompt_text = COALESCE(prompt_text, ''),
            trigger_reason = COALESCE(trigger_reason, 'legacy')
        """
    )
    op.drop_constraint(
        "ck_dynamic_prompt_response_status",
        "dynamic_prompt",
        type_="check",
    )
    op.drop_constraint(
        "ck_dynamic_prompt_escalation_positive",
        "dynamic_prompt",
        type_="check",
    )
    op.alter_column(
        "dynamic_prompt", "trigger_reason", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("dynamic_prompt", "prompt_text", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("dynamic_prompt", "responded_at")
    op.drop_column("dynamic_prompt", "expires_at")
    op.drop_column("dynamic_prompt", "escalation")
    op.drop_index(op.f("ix_missed_response_student_id"), table_name="missed_response")
    op.drop_index(op.f("ix_missed_response_delivery_id"), table_name="missed_response")
    op.drop_table("missed_response")
    op.drop_index(op.f("ix_delivered_question_session_id"), table_name="delivered_question")
    op.drop_index(op.f("ix_delivered_question_question_id"), table_name="delivered_question")
    op.drop_table("delivered_question")
    op.drop_index(op.f("ix_session_participant_student_id"), table_name="session_participant")
    op.drop_index(op.f("ix_session_participant_session_id"), table_name="session_participant")
    op.drop_table("session_participant")
    op.drop_index(op.f("ix_session_activity_session_id"), table_name="session_activity")
    op.drop_index(op.f("ix_session_activity_occurred_at"), table_name="session_activity")
    op.drop_index(op.f("ix_session_activity_event_type"), table_name="session_activity")
    op.drop_index(op.f("ix_session_activity_actor_user_id"), table_name="session_activity")
    op.drop_table("session_activity")
    # ### end Alembic commands ###
