"""create rag chunk table

Revision ID: 89980d5732da
Revises: 53c88e0048bc
Create Date: 2026-08-06 20:01:08.207492

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "89980d5732da"
down_revision: str | Sequence[str] | None = "53c88e0048bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_chunk",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("source_material_id", sa.UUID(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding_vector", Vector(dim=1536), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["source_material.id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        op.f("ix_rag_chunk_source_material_id"), "rag_chunk", ["source_material_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_chunk_source_material_id"), table_name="rag_chunk")
    op.drop_table("rag_chunk")
    # ### end Alembic commands ###
