"""create session table

Revision ID: 8eda16cffa2a
Revises: ac4cc0d3e078
Create Date: 2026-08-06 19:43:12.264548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eda16cffa2a"
down_revision: str | Sequence[str] | None = "ac4cc0d3e078"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("instructor_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(op.f("ix_session_course_id"), "session", ["course_id"], unique=False)
    op.create_index(op.f("ix_session_instructor_id"), "session", ["instructor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_instructor_id"), table_name="session")
    op.drop_index(op.f("ix_session_course_id"), table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
