"""create student response table

Revision ID: 97b8ab121f93
Revises: d1b93a16127a
Create Date: 2026-08-06 20:55:11.527274

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97b8ab121f93"
down_revision: str | Sequence[str] | None = "d1b93a16127a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_response",
        sa.Column("response_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.question_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("response_id"),
    )
    op.create_index(
        op.f("ix_student_response_question_id"), "student_response", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_response_session_id"), "student_response", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_response_student_id"), "student_response", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_response_student_id"), table_name="student_response")
    op.drop_index(op.f("ix_student_response_session_id"), table_name="student_response")
    op.drop_index(op.f("ix_student_response_question_id"), table_name="student_response")
    op.drop_table("student_response")
    # ### end Alembic commands ###
