"""add Teams user mappings

Revision ID: 9a52bced38c2
Revises: e40e0863782e
Create Date: 2026-09-27 22:57:22.239985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a52bced38c2"
down_revision: str | Sequence[str] | None = "e40e0863782e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams_user_mapping",
        sa.Column("mapping_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=256), nullable=False),
        sa.Column("teams_user_id", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("mapping_id"),
        sa.UniqueConstraint(
            "tenant_id", "teams_user_id", name="uq_teams_user_mapping_tenant_teams_user"
        ),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_teams_user_mapping_tenant_user"),
    )
    op.create_index(
        op.f("ix_teams_user_mapping_teams_user_id"),
        "teams_user_mapping",
        ["teams_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_user_mapping_tenant_id"), "teams_user_mapping", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_teams_user_mapping_user_id"), "teams_user_mapping", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_user_mapping_user_id"), table_name="teams_user_mapping")
    op.drop_index(op.f("ix_teams_user_mapping_tenant_id"), table_name="teams_user_mapping")
    op.drop_index(op.f("ix_teams_user_mapping_teams_user_id"), table_name="teams_user_mapping")
    op.drop_table("teams_user_mapping")
    # ### end Alembic commands ###
