"""create student table

Revision ID: ac4cc0d3e078
Revises: e81fb9dbc3f0
Create Date: 2026-08-06 19:35:12.909642

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac4cc0d3e078"
down_revision: str | Sequence[str] | None = "e81fb9dbc3f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("accessibility_need", sa.String(length=255), nullable=True),
        sa.Column("consent_status", sa.String(length=30), nullable=False),
        sa.Column("attention_threshold", sa.String(length=50), nullable=True),
        sa.Column("special_consideration_status", sa.String(length=50), nullable=True),
        sa.Column("enrolled_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("student_id"),
    )
    op.create_index(op.f("ix_student_course_id"), "student", ["course_id"], unique=False)
    op.create_index(op.f("ix_student_user_id"), "student", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_user_id"), table_name="student")
    op.drop_index(op.f("ix_student_course_id"), table_name="student")
    op.drop_table("student")
    # ### end Alembic commands ###
