"""add phase two content pipeline tables

Revision ID: b5c496365765
Revises: cd914692a316
Create Date: 2026-09-17 23:03:53.183493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5c496365765"
down_revision: str | Sequence[str] | None = "cd914692a316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_model_run",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_material_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="ck_ai_model_run_status"
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name="ck_ai_model_run_input_tokens_nonnegative",
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name="ck_ai_model_run_output_tokens_nonnegative",
        ),
        sa.ForeignKeyConstraint(["source_material_id"], ["source_material.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_ai_model_run_source_material_id"),
        "ai_model_run",
        ["source_material_id"],
        unique=False,
    )
    op.create_table(
        "extraction_element",
        sa.Column("element_id", sa.UUID(), nullable=False),
        sa.Column("source_material_id", sa.UUID(), nullable=False),
        sa.Column("element_index", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("element_index >= 0", name="ck_extraction_element_index_nonnegative"),
        sa.CheckConstraint(
            "source_page IS NULL OR source_page >= 1",
            name="ck_extraction_element_source_page_positive",
        ),
        sa.ForeignKeyConstraint(["source_material_id"], ["source_material.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("element_id"),
        sa.UniqueConstraint(
            "source_material_id", "element_index", name="uq_extraction_element_material_index"
        ),
    )
    op.create_index(
        op.f("ix_extraction_element_source_material_id"),
        "extraction_element",
        ["source_material_id"],
        unique=False,
    )
    op.create_table(
        "material_processing_status",
        sa.Column("status_id", sa.UUID(), nullable=False),
        sa.Column("source_material_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("percent", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "stage IN ('validating', 'extracting', 'chunking', "
                "'embedding', 'generating', 'done', 'failed')"
            ),
            name="ck_material_processing_status_stage",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_material_processing_status_sequence_positive"),
        sa.ForeignKeyConstraint(["source_material_id"], ["source_material.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("status_id"),
        sa.UniqueConstraint(
            "source_material_id", "sequence", name="uq_material_processing_status_material_sequence"
        ),
    )
    op.create_index(
        op.f("ix_material_processing_status_source_material_id"),
        "material_processing_status",
        ["source_material_id"],
        unique=False,
    )
    op.add_column("source_material", sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True))
    op.alter_column(
        "source_material",
        "content_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_source_material_uploaded_by_user_id"),
        "source_material",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_source_material_uploaded_by_user_id_user",
        "source_material",
        "user",
        ["uploaded_by_user_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_source_material_uploaded_by_user_id_user",
        "source_material",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_source_material_uploaded_by_user_id"), table_name="source_material")
    op.alter_column(
        "source_material",
        "content_type",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("source_material", "uploaded_by_user_id")
    op.drop_index(
        op.f("ix_material_processing_status_source_material_id"),
        table_name="material_processing_status",
    )
    op.drop_table("material_processing_status")
    op.drop_index(op.f("ix_extraction_element_source_material_id"), table_name="extraction_element")
    op.drop_table("extraction_element")
    op.drop_index(op.f("ix_ai_model_run_source_material_id"), table_name="ai_model_run")
    op.drop_table("ai_model_run")
    # ### end Alembic commands ###
