"""create dynamic prompt table

Revision ID: c3314593349e
Revises: c914a4b3da30
Create Date: 2026-08-06 20:38:02.473705

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3314593349e"
down_revision: str | Sequence[str] | None = "c914a4b3da30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dynamic_prompt",
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("trigger_reason", sa.String(length=255), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("response_status", sa.String(length=30), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("prompt_id"),
    )
    op.create_index(
        op.f("ix_dynamic_prompt_session_id"), "dynamic_prompt", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_dynamic_prompt_student_id"), "dynamic_prompt", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dynamic_prompt_student_id"), table_name="dynamic_prompt")
    op.drop_index(op.f("ix_dynamic_prompt_session_id"), table_name="dynamic_prompt")
    op.drop_table("dynamic_prompt")
    # ### end Alembic commands ###
