"""create engagement record table

Revision ID: c914a4b3da30
Revises: 70bf1eade701
Create Date: 2026-08-06 20:19:39.381699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c914a4b3da30"
down_revision: str | Sequence[str] | None = "70bf1eade701"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagement_record",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("attempt_rate", sa.Float(), nullable=False),
        sa.Column("attention_signal", sa.String(length=50), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        op.f("ix_engagement_record_session_id"), "engagement_record", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_engagement_record_student_id"), "engagement_record", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_engagement_record_student_id"), table_name="engagement_record")
    op.drop_index(op.f("ix_engagement_record_session_id"), table_name="engagement_record")
    op.drop_table("engagement_record")
    # ### end Alembic commands ###
