"""create breakout room table

Revision ID: d1b93a16127a
Revises: c3314593349e
Create Date: 2026-08-06 20:49:15.296720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b93a16127a'
down_revision: Union[str, Sequence[str], None] = 'c3314593349e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout_room',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('silence_duration', sa.Integer(), nullable=False),
    sa.Column('participation_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_breakout_room_session_id'), 'breakout_room', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breakout_room_session_id'), table_name='breakout_room')
    op.drop_table('breakout_room')
    # ### end Alembic commands ###
