"""add Teams meeting persistence

Revision ID: e40e0863782e
Revises: b3c1e7a9d204
Create Date: 2026-09-27 22:32:20.823113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e40e0863782e"
down_revision: str | Sequence[str] | None = "b3c1e7a9d204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams_meeting_link",
        sa.Column("meeting_id", sa.String(length=256), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id"),
        sa.UniqueConstraint(
            "session_id",
            name="uq_teams_meeting_link_session_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teams_meeting_link")
    # ### end Alembic commands ###
